#!/usr/bin/env python3
"""Turns the interface files into a C header, so the program carries them.
Copyright (c) 2026 Reda Cherif-Touil"""
import io, sys
def as_c(name, path):
    data = io.open(path, encoding='utf-8').read()
    out = [f'static const char {name}[] =']
    for line in data.split('\n'):
        line = line.replace('\\', '\\\\').replace('"', '\\"')
        out.append(f'    "{line}\\n"')
    out.append(';')
    return '\n'.join(out)
open(sys.argv[1], 'w').write(
    "/* Generated by tools_embed.py - do not edit. */\n#pragma once\n\n"
    + as_c('UI_INDEX_HTML', 'ui/index.html') + "\n")
print(sys.argv[1], 'ecrit')
